-- MySQL Script generated by MySQL Workbench
-- Ter 23 Jan 2018 21:16:46 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema uvents
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema uvents
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uvents` DEFAULT CHARACTER SET utf8 ;
USE `uvents` ;

-- -----------------------------------------------------
-- Table `uvents`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uvents`.`eventos` (
  `id` INT NOT NULL,
  `foto_evento` VARCHAR(300) NULL,
  `nome_evento` VARCHAR(300) NOT NULL,
  `data_evento` DATE NOT NULL,
  `descricao_evento` LONGTEXT NOT NULL,
  `status` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uvents`.`atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uvents`.`atividade` (
  `id` INT NOT NULL,
  `id_evento` INT NOT NULL,
  `orientador` VARCHAR(100) NOT NULL,
  `nome_atividade` VARCHAR(100) NOT NULL,
  `hora_atividade` DATETIME NOT NULL,
  `data_atividade` DATE NOT NULL,
  `descricao_atividade` LONGTEXT NULL,
  `observacao` LONGTEXT NULL,
  `limite` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_evento_idx` (`id_evento` ASC),
  CONSTRAINT `id_evento`
    FOREIGN KEY (`id_evento`)
    REFERENCES `uvents`.`eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uvents`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uvents`.`tipo_usuario` (
  `id` INT NOT NULL,
  `descricao_` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uvents`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uvents`.`usuario` (
  `id` INT NOT NULL,
  `cpf` VARCHAR(255) NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `id_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_tipo_usuario1_idx` (`id_tipo_usuario` ASC),
  CONSTRAINT `fk_usuario_tipo_usuario1`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `uvents`.`tipo_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uvents`.`usuario_has_atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uvents`.`usuario_has_atividade` (
  `usuario_id` INT NOT NULL,
  `id_atividade` INT NOT NULL,
  `presenca` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `id_atividade`),
  INDEX `fk_usuario_has_atividade_atividade1_idx` (`id_atividade` ASC),
  INDEX `fk_usuario_has_atividade_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_usuario_has_atividade_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `uvents`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_atividade_atividade1`
    FOREIGN KEY (`id_atividade`)
    REFERENCES `uvents`.`atividade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
